import type { Metadata } from "next";
import {DM_Sans } from "next/font/google";
import "./globals.css";

const appFont = DM_Sans({
  subsets: ['latin']
})


export const metadata: Metadata = {
  title: "UIUX mock generator app",
  description: "Generated by damian orina",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      classame={appFont.className}
      >
        {children}
      </body>
    </html>
  );
}
